# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "provisioner" do |provisioner|
    provisioner.vm.box = "ubuntu/xenial64"
    provisioner.vm.box_version = "20180509.0.0"
    provisioner.vm.box_check_update = false
    provisioner.omnibus.chef_version = :latest
    provisioner.vm.network "forwarded_port", guest: 80, host: 8989
    provisioner.vm.provider :virtualbox do |vbox|
      vbox.name = "chef-provisioned"
    end
    provisioner.vm.provision "chef_solo" do |chef|
      chef.node_name = "chef-provisioned"
	    chef.cookbooks_path = "../../cookbooks"
      chef.verbose_logging = true
      chef.add_recipe "learn_chef_apache2"
    end
  end
end
