# -*- mode: ruby -*-
# vi: set ft=ruby :
require "yaml"

unless Vagrant.has_plugin?("vagrant-aws")
  raise 'vagrant-aws plugin is not installed!'
end

Vagrant.configure("2") do |config|
  # Load AWS Properties
  aws_props = YAML.load_file("aws.yml")
  # base box to use for aws
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.omnibus.chef_version = :latest
  config.vm.allowed_synced_folder_types = [:nfs]
  LINUX_NFS_OPTS = ['rw','no_subtree_check','async','all_squash','anongid=1000','anonuid=1000']
  config.vm.synced_folder ".", "/home/ubuntu/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false, linux__nfs_options: LINUX_NFS_OPTS
  config.nfs.functional = false
  # AWS customizations and settings
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "#{aws_props['keys']['access_key_id']}"
    aws.secret_access_key = "#{aws_props['keys']['secret_access_key']}"
    aws.region = "#{aws_props['region_id']}"
    aws.ami = "#{aws_props['ami_id']}"
    aws.instance_type = "#{aws_props['instance_type']}"
    aws.keypair_name = "#{aws_props['keypair_name']}"
    aws.security_groups = "#{aws_props['security_groups']}"
    aws.tags = { "Name" => "#{aws_props['box']['name']}" }

    # AWS Storage:
    aws.block_device_mapping = [{
      'DeviceName' => "/dev/sda1",
      'Ebs.VolumeSize' => "#{aws_props['box']['volume_size']}", # Size in GB
      'Ebs.DeleteOnTermination' => true
    }]
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "#{aws_props['private_key_path']}"
  end

  config.vm.provision "chef_solo" do |chef|
      chef.node_name = "#{aws_props['box']['name']}"
      chef.cookbooks_path = "../../cookbooks"
      chef.add_recipe "cgi_openjdk"
      chef.add_recipe "cgi_docker"
  end

end
